name: MinecartInventory
main: com.github.siloneco.minecartinv.MinecartInventory
version: 1.0.0
author: siloneco
description: "Change inventory when player ride minecart"
commands:
  minecartinventory:
    usage: /{LABEL} set
    permission: minecartinventory.command.minecartinventory
    aliases: ["mi"]
permissions:
  minecartinventory.command.minecartinventory:
    default: op