name: MinecartInventory
main: com.github.siloneco.minecartinv.MinecartInventory
version: 1.0.5
author: siloneco
description: Change inventory when player ride minecart
commands:
  minecartinventory:
    permission: minecartinventory.command.minecartinventory
    aliases:
    - mi
permissions:
  minecartinventory.command.minecartinventory:
    default: op
  minecartinventory.changecartname:
    default: op
  minecartinventory.checkname:
    default: op
  minecartinventory.switchinventory:
    default: true